*&---------------------------------------------------------------------*
*& 包含               Z_01_08TOP
*&---------------------------------------------------------------------*

*
* 声明在程序中将会使用到的表
*
TABLES ZSTUDENT_TABLE .
TABLES ZSCHOOL_TABLE .

" 声明一个内表类型 GTYPE_STUDENT_TOTAL
" 包含字段： 学号，姓名，性别，学校代码，学校名称
TYPES:
  BEGIN OF GTYPE_STUDENT_TOTAL ,
    CODE TYPE ZSTUDENT_TABLE-CODE ,
    NAME TYPE ZSTUDENT_TABLE-NAME ,
    SEX TYPE ZSTUDENT_TABLE-SEX ,
    SCHOOL_CODE TYPE ZSTUDENT_TABLE-SCHOOL_CODE ,
    SCHOOL_NAME TYPE ZSCHOOL_TABLE-SCHOOL_NAME ,
  END OF GTYPE_STUDENT_TOTAL .


" 根据自定义内表类型 声明一个内表，一个结构体
DATA GT_TOTAL TYPE TABLE OF GTYPE_STUDENT_TOTAL .
DATA GS_TOTAL TYPE GTYPE_STUDENT_TOTAL .


" 根据数据库表 ZSCHOOL_TABLE 声明一个内表， 一个结构体
DATA GT_SCHOOL TYPE TABLE OF ZSCHOOL_TABLE .
DATA GS_SCHOOL TYPE ZSCHOOL_TABLE .

" 根据数据库表 ZSTUDENT_TABLE 声明一个内表， 一个结构体
DATA GT_STUDENT TYPE TABLE OF ZSTUDENT_TABLE .
DATA GS_STUDENT TYPE ZSTUDENT_TABLE .


" 声明一个用户命令内表，可获取用户界面点击的相关事件
DATA GT_STATUS LIKE TABLE OF SY-UCOMM WITH HEADER LINE .


" 在屏幕中声明一个区块，含有文本元素 t01
" WITH FRAME 表示带边框线
SELECTION-SCREEN BEGIN OF BLOCK BK1 WITH FRAME TITLE TEXT-T01 .

  " 声明一个行区域
  SELECTION-SCREEN BEGIN OF LINE .
    " 给学生学号字段 的 文本框 添加注释
    SELECTION-SCREEN COMMENT (10) TEXT-T06 FOR FIELD STUCODE .
    " 产生 30 个空格
    SELECTION-SCREEN POSITION 30 .
    " 声明一个 学号的 输入框，参照 GS_STUDENT 结构体的 STUDENT_CODE 字段
    " SELECT-OPTIONS 声明的变量长度不能超过 8
    " NO-EXTENSION 表示不使用 输入扩展按钮
    " NO INTERVALS 表示不使用 区间输入框
    SELECT-OPTIONS STUCODE FOR GS_STUDENT-CODE NO-EXTENSION NO INTERVALS .

    SELECTION-SCREEN POSITION 50 .
    " 对输入框 添加 学号检查结果的 注释
    SELECTION-SCREEN COMMENT (10) GV_RES .
  SELECTION-SCREEN END OF LINE .

  "声明 学生姓名 输入框
  SELECT-OPTIONS STUNAME FOR GS_STUDENT-NAME .

  "声明 学校编号 输入框
  SELECT-OPTIONS SCHCODE FOR GS_SCHOOL-SCHOOL_CODE .

SELECTION-SCREEN END OF BLOCK BK1 .


SELECTION-SCREEN BEGIN OF BLOCK BK2 WITH FRAME TITLE TEXT-T02 .

  SELECTION-SCREEN BEGIN OF LINE .

    PARAMETERS R_MALE RADIOBUTTON GROUP GP1 .
    SELECTION-SCREEN COMMENT (10) TEXT-T04 FOR FIELD R_MALE .

    PARAMETERS R_FEMALE RADIOBUTTON GROUP GP1 .
    SELECTION-SCREEN COMMENT (10) TEXT-T05 FOR FIELD R_FEMALE .

  SELECTION-SCREEN END OF LINE .

SELECTION-SCREEN END OF BLOCK BK2 .

" 在屏幕中加入 3 个空行
SELECTION-SCREEN SKIP 1 .


" CHAR1 选中 X , 不选为空.
" 定义function code HIDE ,点击一次后，执行 PBO 的代码块
PARAMETERS P_CHECK AS CHECKBOX USER-COMMAND HIDE .

SELECTION-SCREEN BEGIN OF BLOCK BK3 WITH FRAME TITLE TEXT-T03 .
  "声明 单选框参数 P_SALES, P_EDU, P_ACC, P_HR ，组名为 GP2
  " MODIF ID 表示 屏幕分组
  PARAMETERS P_SALES RADIOBUTTON GROUP GP2 MODIF ID DEP .
  PARAMETERS P_EDU RADIOBUTTON GROUP GP2 MODIF ID DEP .
  PARAMETERS P_ACC RADIOBUTTON GROUP GP2 MODIF ID DEP .
  PARAMETERS P_HR RADIOBUTTON GROUP GP2 MODIF ID DEP .

SELECTION-SCREEN END OF BLOCK BK3 .



" 从帮助文档中查到下面编写子屏幕的代码

DATA FLAG(1) TYPE C.

* SUBSCREEN 1
" 声明子屏幕1
SELECTION-SCREEN BEGIN OF SCREEN 3001 AS SUBSCREEN .

  SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
    PARAMETERS: P1(10) TYPE C ,
                P2(10) TYPE C ,
                P3(10) TYPE C .
  SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN END OF SCREEN 3001 .


* SUBSCREEN 2
" 声明子屏幕2
SELECTION-SCREEN BEGIN OF SCREEN 3002 AS SUBSCREEN .

  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
    PARAMETERS: Q1(10) TYPE C , " OBLIGATORY ，这个关键字表示是否必输入
                Q2(10) TYPE C ,
                Q3(10) TYPE C .
  SELECTION-SCREEN END OF BLOCK B2 .

SELECTION-SCREEN END OF SCREEN 3002 .


* STANDARD SELECTION SCREEN
" 声明 子屏幕  占用10行区域
" BUTTON1 绑定 PUSH1 指令
" BUTTON2 绑定 PUSH2 指令
SELECTION-SCREEN:
  BEGIN OF TABBED BLOCK MYTAB FOR 10 LINES ,
    TAB (20) BUTTON1 USER-COMMAND PUSH1 ,
    TAB (20) BUTTON2 USER-COMMAND PUSH2 ,
  END OF BLOCK MYTAB .